version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db

  tests:
    build: .
    command: pytest tests/ -v --cov=app
    volumes:
      - .:/app
    depends_on:
      - web